// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.23.0
// source: reservation/reservation-service.proto

package reservation

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeleteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Dlt string `protobuf:"bytes,3,opt,name=dlt,proto3" json:"dlt,omitempty"`
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_reservation_reservation_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reservation_reservation_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_reservation_reservation_service_proto_rawDescGZIP(), []int{0}
}

func (x *DeleteRequest) GetDlt() string {
	if x != nil {
		return x.Dlt
	}
	return ""
}

type DeleteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Dlt string `protobuf:"bytes,4,opt,name=dlt,proto3" json:"dlt,omitempty"`
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_reservation_reservation_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reservation_reservation_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_reservation_reservation_service_proto_rawDescGZIP(), []int{1}
}

func (x *DeleteResponse) GetDlt() string {
	if x != nil {
		return x.Dlt
	}
	return ""
}

type RequestDeleteReservation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Delres string `protobuf:"bytes,3,opt,name=delres,proto3" json:"delres,omitempty"`
}

func (x *RequestDeleteReservation) Reset() {
	*x = RequestDeleteReservation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_reservation_reservation_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestDeleteReservation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestDeleteReservation) ProtoMessage() {}

func (x *RequestDeleteReservation) ProtoReflect() protoreflect.Message {
	mi := &file_reservation_reservation_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestDeleteReservation.ProtoReflect.Descriptor instead.
func (*RequestDeleteReservation) Descriptor() ([]byte, []int) {
	return file_reservation_reservation_service_proto_rawDescGZIP(), []int{2}
}

func (x *RequestDeleteReservation) GetDelres() string {
	if x != nil {
		return x.Delres
	}
	return ""
}

type ResponseDeleteReservation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Delres string `protobuf:"bytes,4,opt,name=delres,proto3" json:"delres,omitempty"`
}

func (x *ResponseDeleteReservation) Reset() {
	*x = ResponseDeleteReservation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_reservation_reservation_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseDeleteReservation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseDeleteReservation) ProtoMessage() {}

func (x *ResponseDeleteReservation) ProtoReflect() protoreflect.Message {
	mi := &file_reservation_reservation_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseDeleteReservation.ProtoReflect.Descriptor instead.
func (*ResponseDeleteReservation) Descriptor() ([]byte, []int) {
	return file_reservation_reservation_service_proto_rawDescGZIP(), []int{3}
}

func (x *ResponseDeleteReservation) GetDelres() string {
	if x != nil {
		return x.Delres
	}
	return ""
}

type RequestAccept struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Acce string `protobuf:"bytes,3,opt,name=acce,proto3" json:"acce,omitempty"`
}

func (x *RequestAccept) Reset() {
	*x = RequestAccept{}
	if protoimpl.UnsafeEnabled {
		mi := &file_reservation_reservation_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestAccept) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestAccept) ProtoMessage() {}

func (x *RequestAccept) ProtoReflect() protoreflect.Message {
	mi := &file_reservation_reservation_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestAccept.ProtoReflect.Descriptor instead.
func (*RequestAccept) Descriptor() ([]byte, []int) {
	return file_reservation_reservation_service_proto_rawDescGZIP(), []int{4}
}

func (x *RequestAccept) GetAcce() string {
	if x != nil {
		return x.Acce
	}
	return ""
}

type ResponseAccept struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Acce string `protobuf:"bytes,4,opt,name=acce,proto3" json:"acce,omitempty"`
}

func (x *ResponseAccept) Reset() {
	*x = ResponseAccept{}
	if protoimpl.UnsafeEnabled {
		mi := &file_reservation_reservation_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseAccept) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseAccept) ProtoMessage() {}

func (x *ResponseAccept) ProtoReflect() protoreflect.Message {
	mi := &file_reservation_reservation_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseAccept.ProtoReflect.Descriptor instead.
func (*ResponseAccept) Descriptor() ([]byte, []int) {
	return file_reservation_reservation_service_proto_rawDescGZIP(), []int{5}
}

func (x *ResponseAccept) GetAcce() string {
	if x != nil {
		return x.Acce
	}
	return ""
}

type Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Request) Reset() {
	*x = Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_reservation_reservation_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_reservation_reservation_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_reservation_reservation_service_proto_rawDescGZIP(), []int{6}
}

func (x *Request) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Greeting string `protobuf:"bytes,2,opt,name=greeting,proto3" json:"greeting,omitempty"`
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_reservation_reservation_service_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_reservation_reservation_service_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_reservation_reservation_service_proto_rawDescGZIP(), []int{7}
}

func (x *Response) GetGreeting() string {
	if x != nil {
		return x.Greeting
	}
	return ""
}

type RequestForReserve struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Reserve *ReserveInfo `protobuf:"bytes,3,opt,name=reserve,proto3" json:"reserve,omitempty"`
}

func (x *RequestForReserve) Reset() {
	*x = RequestForReserve{}
	if protoimpl.UnsafeEnabled {
		mi := &file_reservation_reservation_service_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestForReserve) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestForReserve) ProtoMessage() {}

func (x *RequestForReserve) ProtoReflect() protoreflect.Message {
	mi := &file_reservation_reservation_service_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestForReserve.ProtoReflect.Descriptor instead.
func (*RequestForReserve) Descriptor() ([]byte, []int) {
	return file_reservation_reservation_service_proto_rawDescGZIP(), []int{8}
}

func (x *RequestForReserve) GetReserve() *ReserveInfo {
	if x != nil {
		return x.Reserve
	}
	return nil
}

type ResponseForReserve struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Reserve string `protobuf:"bytes,4,opt,name=reserve,proto3" json:"reserve,omitempty"`
}

func (x *ResponseForReserve) Reset() {
	*x = ResponseForReserve{}
	if protoimpl.UnsafeEnabled {
		mi := &file_reservation_reservation_service_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseForReserve) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseForReserve) ProtoMessage() {}

func (x *ResponseForReserve) ProtoReflect() protoreflect.Message {
	mi := &file_reservation_reservation_service_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseForReserve.ProtoReflect.Descriptor instead.
func (*ResponseForReserve) Descriptor() ([]byte, []int) {
	return file_reservation_reservation_service_proto_rawDescGZIP(), []int{9}
}

func (x *ResponseForReserve) GetReserve() string {
	if x != nil {
		return x.Reserve
	}
	return ""
}

type ReserveInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FromDate      string `protobuf:"bytes,2,opt,name=fromDate,proto3" json:"fromDate,omitempty"`
	ToDate        string `protobuf:"bytes,3,opt,name=toDate,proto3" json:"toDate,omitempty"`
	GuestNumber   int32  `protobuf:"varint,4,opt,name=guestNumber,proto3" json:"guestNumber,omitempty"`
	Accommodation string `protobuf:"bytes,5,opt,name=accommodation,proto3" json:"accommodation,omitempty"`
	Accepted      string `protobuf:"bytes,6,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Acception     string `protobuf:"bytes,7,opt,name=acception,proto3" json:"acception,omitempty"`
}

func (x *ReserveInfo) Reset() {
	*x = ReserveInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_reservation_reservation_service_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReserveInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveInfo) ProtoMessage() {}

func (x *ReserveInfo) ProtoReflect() protoreflect.Message {
	mi := &file_reservation_reservation_service_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveInfo.ProtoReflect.Descriptor instead.
func (*ReserveInfo) Descriptor() ([]byte, []int) {
	return file_reservation_reservation_service_proto_rawDescGZIP(), []int{10}
}

func (x *ReserveInfo) GetFromDate() string {
	if x != nil {
		return x.FromDate
	}
	return ""
}

func (x *ReserveInfo) GetToDate() string {
	if x != nil {
		return x.ToDate
	}
	return ""
}

func (x *ReserveInfo) GetGuestNumber() int32 {
	if x != nil {
		return x.GuestNumber
	}
	return 0
}

func (x *ReserveInfo) GetAccommodation() string {
	if x != nil {
		return x.Accommodation
	}
	return ""
}

func (x *ReserveInfo) GetAccepted() string {
	if x != nil {
		return x.Accepted
	}
	return ""
}

func (x *ReserveInfo) GetAcception() string {
	if x != nil {
		return x.Acception
	}
	return ""
}

type AllReservationsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nothing string `protobuf:"bytes,1,opt,name=nothing,proto3" json:"nothing,omitempty"`
}

func (x *AllReservationsRequest) Reset() {
	*x = AllReservationsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_reservation_reservation_service_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllReservationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllReservationsRequest) ProtoMessage() {}

func (x *AllReservationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reservation_reservation_service_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllReservationsRequest.ProtoReflect.Descriptor instead.
func (*AllReservationsRequest) Descriptor() ([]byte, []int) {
	return file_reservation_reservation_service_proto_rawDescGZIP(), []int{11}
}

func (x *AllReservationsRequest) GetNothing() string {
	if x != nil {
		return x.Nothing
	}
	return ""
}

type AllReservationsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AllAcco []*AllReservationInfo `protobuf:"bytes,1,rep,name=allAcco,proto3" json:"allAcco,omitempty"`
}

func (x *AllReservationsResponse) Reset() {
	*x = AllReservationsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_reservation_reservation_service_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllReservationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllReservationsResponse) ProtoMessage() {}

func (x *AllReservationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reservation_reservation_service_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllReservationsResponse.ProtoReflect.Descriptor instead.
func (*AllReservationsResponse) Descriptor() ([]byte, []int) {
	return file_reservation_reservation_service_proto_rawDescGZIP(), []int{12}
}

func (x *AllReservationsResponse) GetAllAcco() []*AllReservationInfo {
	if x != nil {
		return x.AllAcco
	}
	return nil
}

type AllReservationInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FromDate      string `protobuf:"bytes,2,opt,name=fromDate,proto3" json:"fromDate,omitempty"`
	ToDate        string `protobuf:"bytes,3,opt,name=toDate,proto3" json:"toDate,omitempty"`
	GuestNumber   int32  `protobuf:"varint,4,opt,name=guestNumber,proto3" json:"guestNumber,omitempty"`
	Accommodation string `protobuf:"bytes,5,opt,name=accommodation,proto3" json:"accommodation,omitempty"`
	Accepted      string `protobuf:"bytes,6,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Acception     string `protobuf:"bytes,7,opt,name=acception,proto3" json:"acception,omitempty"`
}

func (x *AllReservationInfo) Reset() {
	*x = AllReservationInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_reservation_reservation_service_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllReservationInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllReservationInfo) ProtoMessage() {}

func (x *AllReservationInfo) ProtoReflect() protoreflect.Message {
	mi := &file_reservation_reservation_service_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllReservationInfo.ProtoReflect.Descriptor instead.
func (*AllReservationInfo) Descriptor() ([]byte, []int) {
	return file_reservation_reservation_service_proto_rawDescGZIP(), []int{13}
}

func (x *AllReservationInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AllReservationInfo) GetFromDate() string {
	if x != nil {
		return x.FromDate
	}
	return ""
}

func (x *AllReservationInfo) GetToDate() string {
	if x != nil {
		return x.ToDate
	}
	return ""
}

func (x *AllReservationInfo) GetGuestNumber() int32 {
	if x != nil {
		return x.GuestNumber
	}
	return 0
}

func (x *AllReservationInfo) GetAccommodation() string {
	if x != nil {
		return x.Accommodation
	}
	return ""
}

func (x *AllReservationInfo) GetAccepted() string {
	if x != nil {
		return x.Accepted
	}
	return ""
}

func (x *AllReservationInfo) GetAcception() string {
	if x != nil {
		return x.Acception
	}
	return ""
}

type CheckRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CheckInfo *CheckReqInfo `protobuf:"bytes,1,opt,name=checkInfo,proto3" json:"checkInfo,omitempty"`
}

func (x *CheckRequest) Reset() {
	*x = CheckRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_reservation_reservation_service_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckRequest) ProtoMessage() {}

func (x *CheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reservation_reservation_service_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckRequest.ProtoReflect.Descriptor instead.
func (*CheckRequest) Descriptor() ([]byte, []int) {
	return file_reservation_reservation_service_proto_rawDescGZIP(), []int{14}
}

func (x *CheckRequest) GetCheckInfo() *CheckReqInfo {
	if x != nil {
		return x.CheckInfo
	}
	return nil
}

type CheckResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CheckRes bool `protobuf:"varint,1,opt,name=checkRes,proto3" json:"checkRes,omitempty"`
}

func (x *CheckResponse) Reset() {
	*x = CheckResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_reservation_reservation_service_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckResponse) ProtoMessage() {}

func (x *CheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reservation_reservation_service_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckResponse.ProtoReflect.Descriptor instead.
func (*CheckResponse) Descriptor() ([]byte, []int) {
	return file_reservation_reservation_service_proto_rawDescGZIP(), []int{15}
}

func (x *CheckResponse) GetCheckRes() bool {
	if x != nil {
		return x.CheckRes
	}
	return false
}

type CheckReqInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccoId   string `protobuf:"bytes,1,opt,name=accoId,proto3" json:"accoId,omitempty"`
	DateFrom string `protobuf:"bytes,2,opt,name=dateFrom,proto3" json:"dateFrom,omitempty"`
	DateTo   string `protobuf:"bytes,3,opt,name=dateTo,proto3" json:"dateTo,omitempty"`
}

func (x *CheckReqInfo) Reset() {
	*x = CheckReqInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_reservation_reservation_service_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckReqInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckReqInfo) ProtoMessage() {}

func (x *CheckReqInfo) ProtoReflect() protoreflect.Message {
	mi := &file_reservation_reservation_service_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckReqInfo.ProtoReflect.Descriptor instead.
func (*CheckReqInfo) Descriptor() ([]byte, []int) {
	return file_reservation_reservation_service_proto_rawDescGZIP(), []int{16}
}

func (x *CheckReqInfo) GetAccoId() string {
	if x != nil {
		return x.AccoId
	}
	return ""
}

func (x *CheckReqInfo) GetDateFrom() string {
	if x != nil {
		return x.DateFrom
	}
	return ""
}

func (x *CheckReqInfo) GetDateTo() string {
	if x != nil {
		return x.DateTo
	}
	return ""
}

var File_reservation_reservation_service_proto protoreflect.FileDescriptor

var file_reservation_reservation_service_proto_rawDesc = []byte{
	0x0a, 0x25, 0x72, 0x65, 0x73, 0x65, 0x72, 0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x72, 0x65,
	0x73, 0x65, 0x72, 0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x21, 0x0a, 0x0d, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x6c, 0x74, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x64, 0x6c, 0x74, 0x22, 0x22, 0x0a, 0x0e, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03,
	0x64, 0x6c, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x64, 0x6c, 0x74, 0x22, 0x32,
	0x0a, 0x18, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52,
	0x65, 0x73, 0x65, 0x72, 0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x65,
	0x6c, 0x72, 0x65, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x65, 0x6c, 0x72,
	0x65, 0x73, 0x22, 0x33, 0x0a, 0x19, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x65, 0x72, 0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x16, 0x0a, 0x06, 0x64, 0x65, 0x6c, 0x72, 0x65, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x64, 0x65, 0x6c, 0x72, 0x65, 0x73, 0x22, 0x23, 0x0a, 0x0d, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x41, 0x63, 0x63, 0x65, 0x70, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x63, 0x63, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x61, 0x63, 0x63, 0x65, 0x22, 0x24, 0x0a, 0x0e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x41, 0x63, 0x63, 0x65, 0x70, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x61, 0x63, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x61, 0x63,
	0x63, 0x65, 0x22, 0x1d, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x22, 0x26, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a,
	0x08, 0x67, 0x72, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x67, 0x72, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x22, 0x3b, 0x0a, 0x11, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x46, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x12, 0x26,
	0x0a, 0x07, 0x72, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0c, 0x2e, 0x52, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x07, 0x72,
	0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x22, 0x2e, 0x0a, 0x12, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x46, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x72, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x72,
	0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x22, 0xc3, 0x01, 0x0a, 0x0b, 0x52, 0x65, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x72, 0x6f, 0x6d, 0x44, 0x61,
	0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x72, 0x6f, 0x6d, 0x44, 0x61,
	0x74, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x6f, 0x44, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x74, 0x6f, 0x44, 0x61, 0x74, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x67, 0x75,
	0x65, 0x73, 0x74, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0b, 0x67, 0x75, 0x65, 0x73, 0x74, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x24, 0x0a, 0x0d,
	0x61, 0x63, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0d, 0x61, 0x63, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x61, 0x63, 0x63, 0x65, 0x70, 0x74, 0x65, 0x64, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x61, 0x63, 0x63, 0x65, 0x70, 0x74, 0x65, 0x64, 0x12, 0x1c,
	0x0a, 0x09, 0x61, 0x63, 0x63, 0x65, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x61, 0x63, 0x63, 0x65, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x32, 0x0a, 0x16,
	0x41, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x65, 0x72, 0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x6e, 0x6f, 0x74, 0x68, 0x69, 0x6e,
	0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6e, 0x6f, 0x74, 0x68, 0x69, 0x6e, 0x67,
	0x22, 0x48, 0x0a, 0x17, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x65, 0x72, 0x76, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2d, 0x0a, 0x07, 0x61,
	0x6c, 0x6c, 0x41, 0x63, 0x63, 0x6f, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x41,
	0x6c, 0x6c, 0x52, 0x65, 0x73, 0x65, 0x72, 0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x07, 0x61, 0x6c, 0x6c, 0x41, 0x63, 0x63, 0x6f, 0x22, 0xda, 0x01, 0x0a, 0x12, 0x41,
	0x6c, 0x6c, 0x52, 0x65, 0x73, 0x65, 0x72, 0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66,
	0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x72, 0x6f, 0x6d, 0x44, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x72, 0x6f, 0x6d, 0x44, 0x61, 0x74, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x74, 0x6f, 0x44, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74,
	0x6f, 0x44, 0x61, 0x74, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x67, 0x75, 0x65, 0x73, 0x74, 0x4e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x67, 0x75, 0x65, 0x73,
	0x74, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x24, 0x0a, 0x0d, 0x61, 0x63, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d,
	0x61, 0x63, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a,
	0x08, 0x61, 0x63, 0x63, 0x65, 0x70, 0x74, 0x65, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x61, 0x63, 0x63, 0x65, 0x70, 0x74, 0x65, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x63, 0x63,
	0x65, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x63,
	0x63, 0x65, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x3b, 0x0a, 0x0c, 0x43, 0x68, 0x65, 0x63, 0x6b,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2b, 0x0a, 0x09, 0x63, 0x68, 0x65, 0x63, 0x6b,
	0x49, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x43, 0x68, 0x65,
	0x63, 0x6b, 0x52, 0x65, 0x71, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x09, 0x63, 0x68, 0x65, 0x63, 0x6b,
	0x49, 0x6e, 0x66, 0x6f, 0x22, 0x2b, 0x0a, 0x0d, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x52, 0x65,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x52, 0x65,
	0x73, 0x22, 0x5a, 0x0a, 0x0c, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x49, 0x6e, 0x66,
	0x6f, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x63, 0x63, 0x6f, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x61, 0x63, 0x63, 0x6f, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x61, 0x74,
	0x65, 0x46, 0x72, 0x6f, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x61, 0x74,
	0x65, 0x46, 0x72, 0x6f, 0x6d, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x61, 0x74, 0x65, 0x54, 0x6f, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x61, 0x74, 0x65, 0x54, 0x6f, 0x32, 0xdc, 0x03,
	0x0a, 0x12, 0x52, 0x65, 0x73, 0x65, 0x72, 0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x2d, 0x0a, 0x14, 0x47, 0x72, 0x65, 0x65, 0x74, 0x46, 0x72, 0x6f,
	0x6d, 0x52, 0x65, 0x73, 0x65, 0x72, 0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x08, 0x2e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x09, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x34, 0x0a, 0x07, 0x52, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x12, 0x12,
	0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x46, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x1a, 0x13, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x46, 0x6f, 0x72,
	0x52, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x22, 0x00, 0x12, 0x4c, 0x0a, 0x11, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x65, 0x72, 0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x19,
	0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65,
	0x73, 0x65, 0x72, 0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x1a, 0x2e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x65, 0x72, 0x76,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x00, 0x12, 0x36, 0x0a, 0x11, 0x41, 0x63, 0x63, 0x65, 0x70,
	0x74, 0x52, 0x65, 0x73, 0x65, 0x72, 0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x2e, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0f, 0x2e, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x2a, 0x0a, 0x11, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x65, 0x72, 0x76, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x12, 0x08, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x09,
	0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3b, 0x0a, 0x18, 0x43,
	0x68, 0x65, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x65, 0x72, 0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x42, 0x79, 0x44, 0x61, 0x74, 0x65, 0x73, 0x12, 0x0d, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0e, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x49, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x41,
	0x6c, 0x6c, 0x52, 0x65, 0x73, 0x65, 0x72, 0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x17,
	0x2e, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x65, 0x72, 0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x73,
	0x65, 0x72, 0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x27, 0x0a, 0x0e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x46, 0x6f, 0x72, 0x47,
	0x75, 0x65, 0x73, 0x74, 0x73, 0x12, 0x08, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x09, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x13, 0x5a, 0x11,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x65, 0x73, 0x65, 0x72, 0x76, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_reservation_reservation_service_proto_rawDescOnce sync.Once
	file_reservation_reservation_service_proto_rawDescData = file_reservation_reservation_service_proto_rawDesc
)

func file_reservation_reservation_service_proto_rawDescGZIP() []byte {
	file_reservation_reservation_service_proto_rawDescOnce.Do(func() {
		file_reservation_reservation_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_reservation_reservation_service_proto_rawDescData)
	})
	return file_reservation_reservation_service_proto_rawDescData
}

var file_reservation_reservation_service_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_reservation_reservation_service_proto_goTypes = []interface{}{
	(*DeleteRequest)(nil),             // 0: DeleteRequest
	(*DeleteResponse)(nil),            // 1: DeleteResponse
	(*RequestDeleteReservation)(nil),  // 2: RequestDeleteReservation
	(*ResponseDeleteReservation)(nil), // 3: ResponseDeleteReservation
	(*RequestAccept)(nil),             // 4: RequestAccept
	(*ResponseAccept)(nil),            // 5: ResponseAccept
	(*Request)(nil),                   // 6: Request
	(*Response)(nil),                  // 7: Response
	(*RequestForReserve)(nil),         // 8: RequestForReserve
	(*ResponseForReserve)(nil),        // 9: ResponseForReserve
	(*ReserveInfo)(nil),               // 10: ReserveInfo
	(*AllReservationsRequest)(nil),    // 11: AllReservationsRequest
	(*AllReservationsResponse)(nil),   // 12: AllReservationsResponse
	(*AllReservationInfo)(nil),        // 13: AllReservationInfo
	(*CheckRequest)(nil),              // 14: CheckRequest
	(*CheckResponse)(nil),             // 15: CheckResponse
	(*CheckReqInfo)(nil),              // 16: CheckReqInfo
}
var file_reservation_reservation_service_proto_depIdxs = []int32{
	10, // 0: RequestForReserve.reserve:type_name -> ReserveInfo
	13, // 1: AllReservationsResponse.allAcco:type_name -> AllReservationInfo
	16, // 2: CheckRequest.checkInfo:type_name -> CheckReqInfo
	6,  // 3: ReservationService.GreetFromReservation:input_type -> Request
	8,  // 4: ReservationService.Reserve:input_type -> RequestForReserve
	2,  // 5: ReservationService.DeleteReservation:input_type -> RequestDeleteReservation
	0,  // 6: ReservationService.AcceptReservation:input_type -> DeleteRequest
	6,  // 7: ReservationService.CheckReservations:input_type -> Request
	14, // 8: ReservationService.CheckReservationsByDates:input_type -> CheckRequest
	11, // 9: ReservationService.GetAllReservations:input_type -> AllReservationsRequest
	6,  // 10: ReservationService.CheckForGuests:input_type -> Request
	7,  // 11: ReservationService.GreetFromReservation:output_type -> Response
	9,  // 12: ReservationService.Reserve:output_type -> ResponseForReserve
	3,  // 13: ReservationService.DeleteReservation:output_type -> ResponseDeleteReservation
	1,  // 14: ReservationService.AcceptReservation:output_type -> DeleteResponse
	7,  // 15: ReservationService.CheckReservations:output_type -> Response
	15, // 16: ReservationService.CheckReservationsByDates:output_type -> CheckResponse
	12, // 17: ReservationService.GetAllReservations:output_type -> AllReservationsResponse
	7,  // 18: ReservationService.CheckForGuests:output_type -> Response
	11, // [11:19] is the sub-list for method output_type
	3,  // [3:11] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_reservation_reservation_service_proto_init() }
func file_reservation_reservation_service_proto_init() {
	if File_reservation_reservation_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_reservation_reservation_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_reservation_reservation_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_reservation_reservation_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestDeleteReservation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_reservation_reservation_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseDeleteReservation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_reservation_reservation_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestAccept); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_reservation_reservation_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseAccept); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_reservation_reservation_service_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_reservation_reservation_service_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_reservation_reservation_service_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestForReserve); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_reservation_reservation_service_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseForReserve); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_reservation_reservation_service_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReserveInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_reservation_reservation_service_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AllReservationsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_reservation_reservation_service_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AllReservationsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_reservation_reservation_service_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AllReservationInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_reservation_reservation_service_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_reservation_reservation_service_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_reservation_reservation_service_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckReqInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_reservation_reservation_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_reservation_reservation_service_proto_goTypes,
		DependencyIndexes: file_reservation_reservation_service_proto_depIdxs,
		MessageInfos:      file_reservation_reservation_service_proto_msgTypes,
	}.Build()
	File_reservation_reservation_service_proto = out.File
	file_reservation_reservation_service_proto_rawDesc = nil
	file_reservation_reservation_service_proto_goTypes = nil
	file_reservation_reservation_service_proto_depIdxs = nil
}
